apiVersion: batch/v1
kind: CronJob
metadata:
  name: observer
  namespace: observer
spec:
  # Run at the top of every hour
  schedule: "* * * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: observer-sa
          containers:
          - name: observer-pod
            image: 863541036173.dkr.ecr.us-east-1.amazonaws.com/observerbot:latest
            imagePullPolicy: Always
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: observer-key
                    key: observer-key
              - name: REPO
                value: eks-anywhere-addons
              - name: OWNER
                value: pjv93
          restartPolicy: Never
